batchsize: 32
batchsize_ul: 128
iteration: 48000
iteration_decay_start: 32000
seed: 0
display_interval: 100
snapshot_interval: 8000
evaluation_interval: 1000

# For evaluation
gamma: 0.01
alpha: 0.01
steps: 5
loss_type: cross_entropy
c_type: square
clip_x: True

models:
   classifier:
      fn: ./classifiers/svhncnn.py
      name: SVHNClassifier
      args:
        n_classes: 10
        activation: relu

dataset:
  dataset_fn: ./datasets/svhn.py
  dataset_name: SVHNSSDataset
  args:
     train: True
     N_l: 1000

dataset_eval:
  dataset_fn: ./datasets/svhn.py
  dataset_name: SVHNDataset
  args:
     train: False

adam:
  alpha: 0.001
  beta1: 0.9
  beta2: 0.999

updater:
  fn: ./updater.py
  name: Updater
  args:
    method: drl
    gamma: 1
    alpha: 0.01
    steps: 5
    loss_type: cross_entropy
    c_type: square
    clip_x: True
